version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: tantal25/foodgram_backend
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/app/backend_static
      - media:/app/media/
  frontend:
    image: tantal25/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: tantal25/foodgram_nginx
    env_file: ../.env
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media/






  
    